name: MCDLink
version: 0.1.0
main: org.loganshaw.mcdlink.MCDLink
description: A bridge between Discord servers and Minecraft servers
author: TheModdedChicken
website: https://loganshaw.org
api-version: '1.20'
softdepend:
  - floodgate