name: MCDLink
version: 0.1.1
main: org.loganshaw.mcdlink.MCDLink
description: A bridge between Discord servers and Minecraft servers
author: TheModdedChicken
website: https://loganshaw.org
api-version: '1.20'
softdepend:
  - floodgate
permissions:
  mcdlink.link:
    description: "Allows a user to link their Discord account"
    default: true
  mcdlink.unlink:
    description: "Allows a user to unlink their Discord account"
    default: true

commands:
  mcd-link:
    description: "Link your Discord account"
    usage: "/mcd-link <code>"
    permission: mcdlink.link
  mcd-unlink:
    description: "Unlink your Discord account"
    usage: "/mcd-unlink"
    permission: mcdlink.unlink